In [1]:
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import numpy as np

In [22]:
i = load_iris()
knn = KNeighborsClassifier(n_neighbors=3)
std = StandardScaler()
gc = GridSearchCV(knn,{'n_neighbors':[i+1 for i in range(10)]},cv=10,)

In [23]:
x_train,x_test,y_train,y_test = train_test_split(i.data,i.target,test_size=0.25)

In [24]:
x_train = std.fit_transform(x_train)
x_test = std.transform(x_test)

In [25]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [26]:
knn.score(x_test,y_test)

0.9473684210526315

In [7]:
my_x_data = np.random.rand(10,4)

In [8]:
my_x_data

array([[0.93408524, 0.54534268, 0.4934046 , 0.86486038],
       [0.55365578, 0.53196787, 0.04139634, 0.56371181],
       [0.04467952, 0.06564716, 0.82766078, 0.49132657],
       [0.26007707, 0.35375057, 0.7067536 , 0.40366832],
       [0.50941388, 0.95254921, 0.08132975, 0.49022733],
       [0.40745182, 0.62302169, 0.63970088, 0.01368103],
       [0.17691569, 0.86564814, 0.45615012, 0.78054318],
       [0.64715221, 0.19421171, 0.61251844, 0.78829272],
       [0.57502658, 0.33514001, 0.28425187, 0.29830081],
       [0.83814247, 0.71179218, 0.81939183, 0.6889768 ]])

In [9]:
my_x_data = std.transform(my_x_data)

In [10]:
my_x_data

array([[-5.95551735, -5.91997477, -1.77422223, -0.38569111],
       [-6.4190085 , -5.95107727, -2.02635618, -0.77476209],
       [-7.03911294, -7.03548455, -1.58777136, -0.86828071],
       [-6.77668621, -6.36551336, -1.65521439, -0.98153139],
       [-6.47291003, -4.97303476, -2.00408099, -0.86970087],
       [-6.59713414, -5.73933581, -1.69261695, -1.48537818],
       [-6.87800477, -5.17511918, -1.79500309, -0.4946253 ],
       [-6.30509838, -6.73651362, -1.70777954, -0.48461322],
       [-6.39297167, -6.40879136, -1.89088935, -1.11766167],
       [-6.07240795, -5.53290412, -1.59238385, -0.61292512]])

In [11]:
knn.predict(my_x_data)

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [12]:
gc.fit(x_train,y_train)

d:\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [13]:
gc.score(x_test,y_test)

0.8947368421052632

In [14]:
gc.best_score_

0.9553571428571429

In [15]:
gc.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [16]:
gc.cv_results_

d:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
d:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
d:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
d:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are acc

{'mean_fit_time': array([0.00019894, 0.        , 0.00029943, 0.00030041, 0.        ,
        0.00039985, 0.00060029, 0.00059965, 0.00019989, 0.00039997]),
 'std_fit_time': array([0.00039788, 0.        , 0.00045739, 0.00045888, 0.        ,
        0.00048972, 0.00091774, 0.00048961, 0.00039978, 0.00048986]),
 'mean_score_time': array([0.00070093, 0.00129852, 0.00079949, 0.00079875, 0.00099964,
        0.00070012, 0.00089886, 0.00090075, 0.00089943, 0.00109935]),
 'std_score_time': array([0.00045887, 0.00064047, 0.00039974, 0.00039938, 0.00044702,
        0.00045834, 0.00083036, 0.0005385 , 0.00053852, 0.00053827]),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 2},
  {'n_neighbors': 3},
  {'n_neighbors': 4},
  {'n_neighbors': 5},
  {'n_neighbors': 6},
